#!/usr/bin/env bash
# export-to-agent.sh
#
# Export one or more skills to a format usable by a specific AI coding agent.
#
# Usage:
#   bash scripts/export-to-agent.sh <target> [<skill> ...]
#
# Targets:
#   codex        — Generate AGENTS.md for GPT Codex CLI (writes to stdout)
#   opencode     — Generate AGENTS.md for OpenCode (writes to stdout)
#   antigravity  — Print install instructions for Antigravity (native SKILL.md)
#   claude       — Print install instructions for Claude Code (native SKILL.md)
#
# Skills:
#   If omitted, exports ALL skills found at the repo root (one section each).
#   If specified, exports only the named skill(s).
#
# Examples:
#   bash scripts/export-to-agent.sh codex                                # all skills → AGENTS.md
#   bash scripts/export-to-agent.sh codex github-git > AGENTS.md         # single skill
#   bash scripts/export-to-agent.sh opencode github-git implementation-quality > AGENTS.md
#   bash scripts/export-to-agent.sh antigravity                          # install help
#   bash scripts/export-to-agent.sh claude                               # install help

set -euo pipefail

# --- locate repo root --------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

# --- usage -------------------------------------------------------------------
usage() {
  sed -n '3,/^set -euo/p' "$0" | head -n -1 | sed 's/^# \?//'
  exit "${1:-0}"
}

if [ $# -lt 1 ]; then
  printf 'ERROR: missing target argument.\n\n' >&2
  usage 1 >&2
fi

TARGET="$1"
shift

case "$TARGET" in
  --help|-h|help) usage 0 ;;
  codex|opencode|antigravity|claude) ;;
  *)
    printf 'ERROR: unknown target "%s". Valid: codex, opencode, antigravity, claude.\n' "$TARGET" >&2
    exit 1
    ;;
esac

# --- determine which skills to export ----------------------------------------
SKILLS=()
if [ $# -eq 0 ]; then
  while IFS= read -r dir; do
    SKILLS+=("$(basename "$dir")")
  done < <(find . -maxdepth 2 -name SKILL.md -printf '%h\n' | sort)
else
  SKILLS=("$@")
fi

# Validate skills exist
for skill in "${SKILLS[@]}"; do
  if [ ! -f "$skill/SKILL.md" ]; then
    printf 'ERROR: skill "%s" not found (looked for %s/SKILL.md)\n' "$skill" "$skill" >&2
    exit 1
  fi
done

if [ ${#SKILLS[@]} -eq 0 ]; then
  printf 'ERROR: no skills found in %s\n' "$REPO_ROOT" >&2
  exit 1
fi

# --- helpers -----------------------------------------------------------------

# Strip the YAML frontmatter from a markdown file, return body only.
strip_frontmatter() {
  awk '
    BEGIN { in_fm = 0; fm_done = 0; }
    /^---$/ && !fm_done {
      if (in_fm == 0) { in_fm = 1; next }
      else            { in_fm = 0; fm_done = 1; next }
    }
    in_fm { next }
    { print }
  ' "$1"
}

# Extract frontmatter description from a SKILL.md (one-liner from YAML).
get_skill_description() {
  awk '
    /^---$/ { fm = !fm; next }
    fm && /^description:/ {
      sub(/^description:[[:space:]]*>?[[:space:]]*/, "")
      print
      exit
    }
  ' "$1"
}

# Render a single skill as one AGENTS.md section.
emit_agents_md_section() {
  local skill="$1"
  local skill_md="$skill/SKILL.md"
  local readme="$skill/README.md"

  printf '\n---\n\n'
  printf '# Skill: %s\n\n' "$skill"

  # Strip frontmatter, inline the SKILL.md body
  strip_frontmatter "$skill_md"

  # If references/ exists, append each file under a clear divider
  if [ -d "$skill/references" ]; then
    printf '\n---\n\n'
    printf '## Reference material — %s\n' "$skill"
    printf '\n*The following sections come from %s/references/. They are inlined here\nso this AGENTS.md is self-contained — no symlinks required.*\n\n' "$skill"
    for ref in "$skill"/references/*.md; do
      [ -f "$ref" ] || continue
      printf '\n### From `%s`\n\n' "$ref"
      strip_frontmatter "$ref"
    done
  fi
}

# --- main: per-target output -------------------------------------------------

case "$TARGET" in

  codex|opencode)
    cat <<EOF
<!--
AGENTS.md generated by agent-skills/scripts/export-to-agent.sh ($TARGET)
Skills included: ${SKILLS[*]}
Source: https://github.com/yogaprastyoo/agent-skills

To regenerate: bash ~/agent-skills/scripts/export-to-agent.sh $TARGET ${SKILLS[*]} > AGENTS.md
-->

# Project conventions ($TARGET)

This file aggregates conventions and constraints from the agent-skills
repository so this agent (\`$TARGET\`) treats them as project-level guidance.

The originals live at: ~/agent-skills/<skill-name>/SKILL.md (and references/).
EOF
    for skill in "${SKILLS[@]}"; do
      emit_agents_md_section "$skill"
    done
    cat <<EOF

---

## Maintenance

This file is generated. Do not edit by hand — changes will be lost the next
time someone regenerates it. To update:

1. Edit the source: \`~/agent-skills/<skill>/SKILL.md\` or \`<skill>/references/*.md\`
2. Open a PR to https://github.com/yogaprastyoo/agent-skills (follow github-git workflow)
3. After merge, regenerate this AGENTS.md:

   \`\`\`bash
   bash ~/agent-skills/scripts/export-to-agent.sh $TARGET ${SKILLS[*]} > AGENTS.md
   \`\`\`

Skills exported in this file: ${SKILLS[*]}
EOF
    ;;

  antigravity)
    cat <<EOF
# Antigravity CLI — install instructions

Antigravity reads the same \`SKILL.md\` format as Claude Code, so no AGENTS.md
export is needed. Antigravity already shares the skills folder via this
symlink chain (set up earlier):

  ~/.gemini/antigravity/skills → ~/.agents/skills

To verify Antigravity sees the skills:

  ls ~/.gemini/antigravity/skills/

You should see: ${SKILLS[*]}

If the symlink is missing or broken:

  # Re-establish the symlink
  ln -s ~/agent-skills ~/.gemini/antigravity/skills

Restart Antigravity and the skills load automatically.
EOF
    ;;

  claude)
    cat <<EOF
# Claude Code — install instructions

Claude Code reads the \`SKILL.md\` format natively, so no AGENTS.md export
is needed. Symlink the skills you want into ~/.claude/skills/:

  git clone https://github.com/yogaprastyoo/agent-skills.git ~/agent-skills
  mkdir -p ~/.claude/skills
EOF
    for skill in "${SKILLS[@]}"; do
      printf '  ln -s ~/agent-skills/%s ~/.claude/skills/%s\n' "$skill" "$skill"
    done
    cat <<EOF

For full install (slash commands + hooks for github-git), see:

  ~/agent-skills/github-git/README.md → "Install" section

Verify with:

  bash ~/agent-skills/github-git/scripts/verify-install.sh
EOF
    ;;
esac
